### ISSUE TITLE
Could not find or load main class bdv.bigcat.BigCatRemoteClient

### ISSUE THREAD

**Issue by jni** [saalfeldlab/bigcat-launch#1]
Hey @axtimwalde!

I tried the launch script on a new machine, and get the following error:

```
Error: Could not find or load main class bdv.bigcat.BigCatRemoteClient
```

<details>
<summary>

Here's the rest of the error message:</summary>

```
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building BIGCAT 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- build-helper-maven-plugin:1.9.1:regex-property (sanitize-version) @ bigcat ---
[INFO]
[INFO] --- buildnumber-maven-plugin:1.3:create (default) @ bigcat ---
[INFO] Executing: /bin/sh -c cd /Users/nuneziglesiasj/projects/bigcat-launch/bigcat && git rev-parse --verify HEAD
[INFO] Working directory: /Users/nuneziglesiasj/projects/bigcat-launch/bigcat
[INFO] Storing buildNumber: 50d658ae29c6b880605ec14cda1ab8eb07df1bb4 at timestamp: 1477028589896
[INFO] Storing buildScmBranch: remote-client
[INFO]
[INFO] --- scijava-maven-plugin:0.5.1:set-rootdir (set-rootdir) @ bigcat ---
[INFO] Setting rootdir: /Users/nuneziglesiasj/projects/bigcat-launch/bigcat
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ bigcat ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 7 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.3:compile (default-compile) @ bigcat ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ bigcat ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/nuneziglesiasj/projects/bigcat-launch/bigcat/src/test/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.3:testCompile (default-testCompile) @ bigcat ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-surefire-plugin:2.17:test (default-test) @ bigcat ---
[INFO] Surefire report directory: /Users/nuneziglesiasj/projects/bigcat-launch/bigcat/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running bdv.img.h5.H5UtilsTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.059 sec <<< FAILURE! - in bdv.img.h5.H5UtilsTest
bdv.img.h5.H5UtilsTest  Time elapsed: 0.058 sec  <<< ERROR!
java.io.IOException: Could not create test directory for HDF5Utils test.
    at bdv.img.h5.H5UtilsTest.setUpBeforeClass(H5UtilsTest.java:68)

Running bdv.util.IdServiceTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.035 sec - in bdv.util.IdServiceTest
Running bdv.util.LocalIdServiceTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.005 sec - in bdv.util.LocalIdServiceTest

Results :

Tests in error:
  H5UtilsTest.setUpBeforeClass:68 IO Could not create test directory for HDF5Uti...

Tests run: 3, Failures: 0, Errors: 1, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.519 s
[INFO] Finished at: 2016-10-21T16:43:11+11:00
[INFO] Final Memory: 23M/309M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.17:test (default-test) on project bigcat: There are test failures.
[ERROR]
[ERROR] Please refer to /Users/nuneziglesiasj/projects/bigcat-launch/bigcat/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building BIGCAT 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-dependency-plugin:2.8:build-classpath (default-cli) @ bigcat ---
[INFO] Skipped writing classpath file '/Users/nuneziglesiasj/projects/bigcat-launch/bigcat/cp.txt'.  No changes found.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.577 s
[INFO] Finished at: 2016-10-21T16:43:24+11:00
[INFO] Final Memory: 23M/309M
[INFO] ------------------------------------------------------------------------
Error: Could not find or load main class bdv.bigcat.BigCatRemoteClient
```

</details>

Any ideas? My Maven version is 3.3.9. I'm also using Oracle's JDK — let me know if you think that could be the issue.

**Comment by axtimwalde** [comment]
Branch remote-client?

On October 21, 2016 1:49:17 AM EDT, Juan Nunez-Iglesias notifications@github.com wrote:

> Hey @axtimwalde!
> 
> I tried the launch script on a new machine, and get the following
> error:
> 
> ```
> Error: Could not find or load main class bdv.bigcat.BigCatRemoteClient
> ```
> 
> <details>
> <summary>
> 
> Here's the rest of the error message:</summary>
> 
> 
> 
> ```
> [INFO] Scanning for projects...
> [INFO]
> [INFO]
> ------------------------------------------------------------------------
> [INFO] Building BIGCAT 0.0.1-SNAPSHOT
> [INFO]
> ------------------------------------------------------------------------
> [INFO]
> [INFO] --- build-helper-maven-plugin:1.9.1:regex-property
> (sanitize-version) @ bigcat ---
> [INFO]
> [INFO] --- buildnumber-maven-plugin:1.3:create (default) @ bigcat ---
> [INFO] Executing: /bin/sh -c cd
> /Users/nuneziglesiasj/projects/bigcat-launch/bigcat && git rev-parse
> --verify HEAD
> [INFO] Working directory:
> /Users/nuneziglesiasj/projects/bigcat-launch/bigcat
> [INFO] Storing buildNumber: 50d658ae29c6b880605ec14cda1ab8eb07df1bb4 at
> timestamp: 1477028589896
> [INFO] Storing buildScmBranch: remote-client
> [INFO]
> [INFO] --- scijava-maven-plugin:0.5.1:set-rootdir (set-rootdir) @
> bigcat ---
> [INFO] Setting rootdir:
> /Users/nuneziglesiasj/projects/bigcat-launch/bigcat
> [INFO]
> [INFO] --- maven-resources-plugin:2.6:resources (default-resources) @
> bigcat ---
> [INFO] Using 'UTF-8' encoding to copy filtered resources.
> [INFO] Copying 7 resources
> [INFO]
> [INFO] --- maven-compiler-plugin:3.3:compile (default-compile) @ bigcat
> ---
> [INFO] Nothing to compile - all classes are up to date
> [INFO]
> [INFO] --- maven-resources-plugin:2.6:testResources
> (default-testResources) @ bigcat ---
> [INFO] Using 'UTF-8' encoding to copy filtered resources.
> [INFO] skip non existing resourceDirectory
> /Users/nuneziglesiasj/projects/bigcat-launch/bigcat/src/test/resources
> [INFO]
> [INFO] --- maven-compiler-plugin:3.3:testCompile (default-testCompile)
> @ bigcat ---
> [INFO] Nothing to compile - all classes are up to date
> [INFO]
> [INFO] --- maven-surefire-plugin:2.17:test (default-test) @ bigcat ---
> [INFO] Surefire report directory:
> /Users/nuneziglesiasj/projects/bigcat-launch/bigcat/target/surefire-reports
> 
> -------------------------------------------------------
> T E S T S
> -------------------------------------------------------
> Running bdv.img.h5.H5UtilsTest
> Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.059
> sec <<< FAILURE! - in bdv.img.h5.H5UtilsTest
> bdv.img.h5.H5UtilsTest  Time elapsed: 0.058 sec  <<< ERROR!
> java.io.IOException: Could not create test directory for HDF5Utils
> test.
>   at bdv.img.h5.H5UtilsTest.setUpBeforeClass(H5UtilsTest.java:68)
> 
> Running bdv.util.IdServiceTest
> Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.035
> sec - in bdv.util.IdServiceTest
> Running bdv.util.LocalIdServiceTest
> Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.005
> sec - in bdv.util.LocalIdServiceTest
> 
> Results :
> 
> Tests in error:
> H5UtilsTest.setUpBeforeClass:68 IO Could not create test directory for
> HDF5Uti...
> 
> Tests run: 3, Failures: 0, Errors: 1, Skipped: 0
> 
> [INFO]
> ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO]
> ------------------------------------------------------------------------
> [INFO] Total time: 2.519 s
> [INFO] Finished at: 2016-10-21T16:43:11+11:00
> [INFO] Final Memory: 23M/309M
> [INFO]
> ------------------------------------------------------------------------
> [ERROR] Failed to execute goal
> org.apache.maven.plugins:maven-surefire-plugin:2.17:test (default-test)
> on project bigcat: There are test failures.
> [ERROR]
> [ERROR] Please refer to
> /Users/nuneziglesiasj/projects/bigcat-launch/bigcat/target/surefire-reports
> for the individual test results.
> [ERROR] -> [Help 1]
> [ERROR]
> [ERROR] To see the full stack trace of the errors, re-run Maven with
> the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR]
> [ERROR] For more information about the errors and possible solutions,
> please read the following articles:
> [ERROR] [Help 1]
> http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
> [INFO] Scanning for projects...
> [INFO]
> [INFO]
> ------------------------------------------------------------------------
> [INFO] Building BIGCAT 0.0.1-SNAPSHOT
> [INFO]
> ------------------------------------------------------------------------
> [INFO]
> [INFO] --- maven-dependency-plugin:2.8:build-classpath (default-cli) @
> bigcat ---
> [INFO] Skipped writing classpath file
> '/Users/nuneziglesiasj/projects/bigcat-launch/bigcat/cp.txt'.  No
> changes found.
> [INFO]
> ------------------------------------------------------------------------
> [INFO] BUILD SUCCESS
> [INFO]
> ------------------------------------------------------------------------
> [INFO] Total time: 1.577 s
> [INFO] Finished at: 2016-10-21T16:43:24+11:00
> [INFO] Final Memory: 23M/309M
> [INFO]
> ------------------------------------------------------------------------
> Error: Could not find or load main class bdv.bigcat.BigCatRemoteClient
> ```
> 
> </details>
> 
> Any ideas? My Maven version is 3.3.9. I'm also using Oracle's JDK — let
> me know if you think that could be the issue.
> 
> ## 
> 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/saalfeldlab/bigcat-launch/issues/1

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by jni** [comment]
It would be worrisome if that was the issue, since we specify the branch in the launch script... At any rate I just verified that the class is there and the branch is correct:

``` console
nuneziglesiasj@jni-lscc-mbp Wed Oct 26 09:15
 ~/projects/bigcat-launch/bigcat/src/main/java/bdv/bigcat (remote-client)$ ls
BigCat.java             Config.java             label
BigCatAriadne.java      Message.java            ui
BigCatRemoteClient.java annotation              util
BigCatShowPadded.java   composite
CombinedImgLoader.java  control
```

I just followed the error message in the original post to the test failures and found this:

``` console
nuneziglesiasj@jni-lscc-mbp Wed Oct 26 09:20
 ~/projects/bigcat-launch/bigcat/target/surefire-reports (remote-client)$ cat bdv.img.h5.H5UtilsTest.txt
-------------------------------------------------------------------------------
Test set: bdv.img.h5.H5UtilsTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.059 sec <<< FAILURE! - in bdv.img.h5.H5UtilsTest
bdv.img.h5.H5UtilsTest  Time elapsed: 0.058 sec  <<< ERROR!
java.io.IOException: Could not create test directory for HDF5Utils test.
        at bdv.img.h5.H5UtilsTest.setUpBeforeClass(H5UtilsTest.java:68)
```

=\

**Comment by axtimwalde** [comment]
That means you cannot create `System.getProperty( "user.home" ) + "/tmp/bigcat-test/"`which is indeed surprising.  `System.getProperty( "user.home" )` is supposed to be `$HOME`.
